import { FC, useState } from "react";
import { Button, Input, SubmitButton } from "@chainkeeping/ui";
import Modal from "../molecules/two-factor-authenticator-modal";
import CopyIcon from "@/pattern/taxes/atoms/copy-icon";

interface ModalComponentProps {
	isOpen: boolean;
	onClose: () => void;
}

const TwoFAModal: FC<ModalComponentProps> = ({ isOpen, onClose }) => {
	const [otp, setOtp] = useState<string[]>(Array(6).fill(""));

	const handleInputChange = (value: string, index: number) => {
		if (value.length > 1) return; // Prevent more than one character
		const updatedOtp = [...otp];
		updatedOtp[index] = value;
		setOtp(updatedOtp);

		// Focus the next input field if available
		if (value && index < otp.length - 1) {
			const nextInput = document.getElementById(`otp-input-${index + 1}`);
			nextInput?.focus();
		}
	};

	const handleKeyDown = (
		event: React.KeyboardEvent<HTMLInputElement>,
		index: number
	) => {
		if (event.key === "Backspace" && !otp[index] && index > 0) {
			const prevInput = document.getElementById(`otp-input-${index - 1}`);
			prevInput?.focus();
		}
	};

	return (
		<Modal isOpen={isOpen} onClose={onClose} title='Two-Factor Authentication'>
			<div className='p-4 flex justify-between gap-4'>
				<div className='w-full lg:max-w-[437px] flex flex-col gap-4'>
					<div>
						<h6>Step 1</h6>
						<p className='text-grey-500 text-sm'>
							Install an authenticator app like Authy or Google Authenticator.
						</p>
					</div>
					<div>
						<h6>Step 2</h6>
						<p className='text-grey-500 text-sm'>
							Scan the QR Code below with your authenticator app. If you can’t
							scan the code, manually enter the text code below into the
							authenticator app instead.
						</p>
					</div>
					<div className='flex border rounded-md border-border border-dashed w-full justify-between p-2'>
						<p className='text-sm text-grey-400'>CNYVQQRXPMHFAJAF</p>
						<CopyIcon />
					</div>
					<div>
						<h6>Step 3</h6>
						<p className='text-grey-500 text-sm'>
							Enter the OTP generated by the app and click enable 2-FA.
						</p>
						<div className='flex gap-2 mt-10'>
							{otp.map((digit, index) => (
								<input
									key={index}
									id={`otp-input-${index}`}
									type='text'
									value={digit}
									placeholder='-'
									onChange={(e) => handleInputChange(e.target.value, index)}
									onKeyDown={(e) => handleKeyDown(e, index)}
									maxLength={1}
									className='w-12 h-12 border rounded-md text-center text-xl focus:outline-none focus:ring-2 focus:ring-secondary'
								/>
							))}
						</div>
					</div>
				</div>
				<div className='flex flex-col justify-between'>
					<img src='/QRCode.svg' alt='' />
					<Button variant='default' size='md' className='w-full text-base'>
						Enable 2FA
					</Button>
				</div>
			</div>
		</Modal>
	);
};

export default TwoFAModal;
