import "@chainkeeping/ui/dist/index.css";
import "./assets/styles/globals.css";

import type { Metadata } from "next";
import { dmsans, inter, rubik, sen, space_Grotesk } from "./assets/fonts";
import { Providers } from "../redux/provider";


import { Provider as RollbarProvider } from '@rollbar/react';
import { clientConfig } from "@/lib/utils/rollbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <RollbarProvider config={clientConfig}>
      <html lang="en">
      <body className={`${sen.variable} ${inter.variable} ${dmsans.variable} ${rubik.variable} ${space_Grotesk.variable} antialiased relative bg-background w-screen min-h-svh h-fit m-0 p-0 overflow-x-hidden`} >
          <Providers>{children}</Providers>
        </body>
      </html>
    // </RollbarProvider >
  );
}
