import "@chainkeeping/ui/dist/index.css";
import "./styles/globals.css";

import type { Metadata } from "next";
import { inter, sen } from "./fonts";
import { Providers } from "../redux/provider";


import { Provider as RollbarProvider } from '@rollbar/react';
import { clientConfig } from "@/lib/utils/rollbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RollbarProvider config={clientConfig}>
      <html lang="en">
        <body className={`${sen.variable} ${inter.variable} antialiased relative bg-background w-screen min-h-screen h-fit m-0 p-0 overflow-hidden`} >
          <Providers>{children}</Providers>
        </body>
      </html>
    </RollbarProvider >
  );
}
